# Generated by Django 5.2.5 on 2025-08-09 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_type', models.CharField(max_length=50)),
                ('case_number', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=4)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('raw_response', models.TextField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CaseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parties', models.TextField()),
                ('filing_date', models.DateField(blank=True, null=True)),
                ('next_hearing', models.DateField(blank=True, null=True)),
                ('orders', models.JSONField(default=list)),
                ('query', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='case_fetcher.casequery')),
            ],
        ),
    ]
